config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations", omniauth_callbacks: "omniauth_callbacks"  }

  root 'static_pages#index'

  get 'dashboard' => 'users#dashboard'

  resources :activities

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  validates_presence_of :name, :location, :time, :date, :user_id

  belongs_to :user
end

app/models/eventful_api.rb
class EventfulApi
  include HTTParty

  # "ADD IN RESCUE WHEN THERE ARE NO EVENTS AVAILABLE"

  def self.getData(params)
    res = HTTParty.get("http://api.eventful.com/json/events/search?c=" + EventfulApi.sanitize_search_term_params(params[:searchTerm]) + "&l=" + params[:searchLocation] + "&within=" + params[:searchRadius] + "&date=" + params[:searchDate] + "&app_key=#{ENV["eventful_api_key"]}")
    data = JSON.parse(res.body)
    events = []

    begin
      data["events"]["event"].each do |e|
        event = {}
        event["category"] = params[:searchTerm]
        event["name"] = e["title"]
        event["description"] = ActionView::Base.full_sanitizer.sanitize(e["description"])
        event["date"] = DateTime.parse(e["start_time"]).strftime("%B %d, %Y")
        event["time"] = DateTime.parse(e["start_time"]).strftime("%l:%M %p")
        event["venue_name"] = e["venue_name"]
        event["address"] = e["venue_address"]
        event["city"] = e["city"]
        event["state"] = e["region_name"]
        event["zip_code"] = e["postal_code"]
        event["country"] = e["country_name"]
        event["address_string"] = "#{event["address"]} #{event["city"]} #{event["state"]} #{event["zip_code"]} #{event["country"]}"

        events << event
      end
    rescue => error
      []
    end
    events
  end

  protected

  def self.sanitize_search_term_params(search_term)
    # add `return` to add clarity
    case search_term
      when "comedy shows"
        return "comedy"
      when "movies & films"
        return "movies_film"
      when "performing arts"
        return "performing_arts"
      when "kids & family"
        return "family_fun_kids"
      when "festivals"
        return "festivals_parades"
      when "food & wine"
        return "food"
      when "art galleries & exhibits"
         return "art"
      when "museums & attractions"
        return "attractions"
      when  "neigborhood activities"
        return "community"
      when "nightlife & singles"
        return "singles_social"
      when "outdoors & recreation"
        return "outdoors_recreation"
      else
        return search_term
      end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  validates_presence_of :email, :first_name, :last_name
  validates_presence_of :password, on: :create
  validates_uniqueness_of :email

  has_many :activities

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.first_name = auth.info.name.split(' ').first
      user.last_name = auth.info.name.split(' ').last
      user.full_name = auth.info.name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]

      # user.image = auth.info.image # assuming the user model has an image
    end
  end

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  skip_before_action :verify_authenticity_token

  EVENTFUL_API_SEARCH_TERMS = ["sports", "movies & films", "performing arts", "music", "museums & attractions", "festivals", "comedy", "conference", "neigborhood activities", "nightlife & singles", "art galleries & exhibits",  "outdoors & recreation", "food & wine", "kids & family"]

  def index
    @user = current_user
    @activities = []
    if EVENTFUL_API_SEARCH_TERMS.include?(activity_search_params[:searchTerm])
      @activities = EventfulApi.getData(params)
    end

    if activity_search_params[:isHeaderSearchSelector] == "true"
      if @activities.empty?
        flash[:notice] = "Sorry, but there were no results based on your search."
      end
      render :js => "window.location = '#{activities_path(params.merge(isHeaderSearchSelector:'false'))}'"
    else
      respond_to do |format|
        format.html
        format.js {
          if @activities.empty?
            flash.now[:notice] = "Sorry, but there were no results based on your search."
          end
          render "get_activity", collection: @activities
          }
      end
    end
  end

  def create
    @activity = current_user.activities.new(activity_creation_params)
    if @activity.save!
      respond_to do |format|
        format.json  { head :ok }
      end
    else
      flash.now[:notice] = "Sorry for the inconvience, but this activity can not be saved at this time."
    end
  end

  def destroy
    Activity.find(params["id"]).delete
    @activities = Activity.all.where(user_id: current_user.id).all
    # flash[:notice] = "Your activity has been deleted."
    render "users/activities_update", collection: @activities
  end

  protected

  def activity_search_params
    params.permit(:searchTerm, :searchDate, :searchLocation, :searchRadius, :isHeaderSearchSelector)
  end

  def activity_creation_params
    params.permit(:name, :venue_name, :time, :date, :location, :description)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(resource)
    flash.notice = "Welcome back, #{current_user.first_name} #{current_user.last_name}!"
    '/dashboard'
  end

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit :first_name, :last_name, :email, :password, :password_confirmation
    end
    devise_parameter_sanitizer.for(:account_update) do |u|
        u.permit :first_name, :last_name, :email, :password, :password_confirmation,
        :current_password
    end
  end

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def update_resource(resource, params)
    if current_user.provider == "facebook"
      params.delete("current_password")
      resource.update_without_password(params)
    else
      resource.update_with_password(params)
    end
  end

  protected

  def after_sign_up_path_for(resource)
    flash.notice = "Welcome to Not Bored Tonight, #{current_user.first_name}
                                                  #{current_user.last_name}!"
    dashboard_path
  end

  def after_update_path_for(resource)
    flash.notice = "Your account has been successfully updated!"
    dashboard_path
  end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
    @user = current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def dashboard
    @user = current_user
    @activities = current_user.activities
    render 'dashboard'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/_activities.html.haml
- unless @activities.empty?
  - if DateTime.now < Date.parse(@activities[0]["date"])
    %h2= @activities[0]["category"].upcase
    .search-results
      - @activities.each do |activity|

        .search-results__activity{ id: "#{activity["name"]}" }

          %h3.activity__name= activity["name"]

          %h4.activity__venue-name--label Venue:
          %h5.activity__venue-name= activity["venue_name"]
          %h6.activity__location= activity["address_string"]

          %h4.activity__date-time--label When:
          %h6.activity__date-time= " #{activity["date"]} @ #{activity["time"].strip}"

          - unless "#{activity["description"]}".length == 0
            .activity__more-info
              %a{ id: "more-info" } More Information
              %p.activity__description.hidden= activity["description"].lstrip

          .save-to-calendar
            - if user_signed_in?
              %button.save-to-calendar__signed-in#save-activity{:href => "#", remote: :true} Save

            -else
              %button.save-to-calendar__disabled{:href => "#", disabled: "disabled"} Save
              %p.require-sign-in
                Want to save this event to your calender?
                %a{ href: "#" } Sign In
                or
                %a{ href: "#{new_user_registration_path}"} Sign Up
                for an account
  - else
    - flash.now[:notice] = "Sorry, but there were no results based on your search."

app/views/activities/get_activity.js.erb
<% if notice %>
  $(".notice").empty().append("<p><%= notice %></p>");
  $("#search-results").empty();
<% else %>
  $(".notice").empty();
  $('#search-results').empty().html('<%= j render "activities" %>');x
<% end %>

app/views/activities/index.html.haml
.search-container
  .search-container__navigation
    %h2 Find Activities
    .navigation__query-choices
      %button.query-item{ href: "#" } Sports
      %button.query-item{ href: "#" } Music
      %button.query-item{ href: "#" } Food & Wine
      %button.query-item{ href: "#" } Museums & Attractions
      %button.query-item{ href: "#" } Festivals
      %button.query-item{ href: "#" } Kids & Family
      %ul.accordion
        %li
          %button.more-activities-button.js-accordion-trigger{href: "#"} More Activities
          %ul.submenu
            %li
              %button.query-item{ href: "#" } Art Galleries & Exhibits
            %li
              %button.query-item{ href: "#" } Performing Arts
            %li
              %button.query-item{ href: "#" } Movies & Films
            %li
              %button.query-item{ href: "#" } Neigborhood Activities
            %li
              %button.query-item{ href: "#" } Nightlife & Singles
            %li
              %button.query-item{ href: "#" } Comedy Shows
            %li
              %button.query-item{ href: "#" } Various Meetups
            %li
              %button.query-item{ href: "#" } Conferences
            %li
              %button.query-item{ href: "#" } Outdoors & Recreation
    .navigation__parameters
      %ul.accordion
        %li
          %button.search-parameters.js-accordion-trigger{href: "#"} Search Parameters
          %ul.submenu
            %li
              %label.param-label Zip Code
              %input{ autofocus: true, id: "search-location", class: "params" }
            %li
              %label.param-label Search Radius
              %select{ id: "search-radius", class: "params" }
                - ((5..100).step(5).to_a).each do |i|
                  - if i == 20
                    %option{ selected: "selected" } 20
                  - else
                    %option #{i}
            %li
              %label.param-label How soon?
              %select{ id: "search-date", class: "params" }
                %option Today
                %option Tomorrow
                %option{ selected: "selected" } This Week
                %option Next Week
  .search-container__search-results#search-results
    = render "activities"

app/views/layouts/_footer.html.haml
%footer.footer
  .footer-logo
    %img{ alt: "Logo image", src: "https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_1.png" }/
  %ul
    %li
      = link_to "About Us", '#'
    %li
      = link_to "Blog", '#'
    %li
  .footer-secondary-links
    %ul
      %li
        = link_to "Term and Condtions", '#'
      %li
        = link_to "Privacy Policy", '#'
    %ul.footer-social
      %li
        %a{ href: "#" }
          %img{ alt: "Facebook", src: "assets/icon-facebook.png" }/
      %li
        %a{ href: "#" }
          %img{ alt: "Twitter", src: "assets/icon-twitter.png" }/

app/views/layouts/_header.html.haml
%header.header__navigation
  .navigation-wrapper
    .navigation__logo
      .logo.nav-link
        %h1= link_to "Not Bored Tonight", root_path
    .nav
      %ul#navigation-menu
        %li.browse-menu__query-item.nav-link
          = link_to "Sports", "#"
        %li.browse-menu__query-item.nav-link
          = link_to "Music", "#"
        %li.browse-menu__query-item.nav-link
          = link_to "Family", "#"
        %li.browse-menu__query-item.nav-link
          = link_to "Festivals", "#"
        %li.browse-menu__query-item.nav-link
          = link_to "More", activities_path
        - if signed_in?
          %li.nav-link.more.user
            %a #{@user.first_name}
            %ul.submenu
              %li
                = link_to "Dashboard", dashboard_path
              %li
                = link_to "Sign Out", destroy_user_session_path, method: :delete
              %li
                = link_to "Edit Profile", edit_user_registration_path
        - else
          %li.nav-link.user
            = link_to "Log In", new_user_session_path

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title Not Bored Tonight
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body

    = render 'layouts/header'

    %p.notice= notice
    %p.alert= alert

    .wrapper-for-content-outside-of-footer
      .contents
        = yield
      .push

    = render 'layouts/footer'

    = javascript_include_tag "application"

app/views/static_pages/index.html.haml
.home-page-container
  .browsers
    .browser
      .browser-top-bar
        .browser-circle
        .browser-circle
        .browser-circle
      .browser-content
    .browser
      .browser-top-bar
        .browser-circle
        .browser-circle
        .browser-circle
      .browser-content
    .browser
      .browser-top-bar
        .browser-circle
        .browser-circle
        .browser-circle
      .browser-content
  .cover

  %ul.bullets
    %li.bullet.three-col-bullet
      .bullet-icon.bullet-icon-1
        %img{ alt: "", src: "https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_2.png\r\n"}/
      .bullet-content
        %h2 Bored?
        %p Too many people sit at home after a long day at work, bored out of their minds. You don't have to be one of those people!
    %li.bullet.three-col-bullet
      .bullet-icon.bullet-icon-2
        %img{alt: "", src: "https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_3.png"}/
      .bullet-content
        %h2 Find Activities
        %p With our comprehensive search, you can find numerous activities in your area. When you are looking to do a activity, you can control the area of your search and what type of activity you are in the mood for!
    %li.bullet.three-col-bullet
      .bullet-icon.bullet-icon-3
        %img{ alt: "", src: "https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_4.png"}/
      .bullet-content
        %h2 Add to Calendar
        %p You can save activities to your calendar so that time and forgetfulness don't get the best of you!

app/views/users/_user_activities.html.haml
- unless @activities.empty?
  .cards
    %h2= @activities[0]["category"]
    - @activities.each do |activity|
      - unless DateTime.now > Date.parse(activity["date"])
        .card.user-activity{ id: "#{activity["name"]}" }
          .activity__delete-from-calendar= link_to 'X', activity_path(activity["id"]), :method => :delete, :remote => true
          .card-image
            %img{alt: "", :src => "https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/mountains.png"}/
          .card-header
            .user-activity__name
              %h5= activity["name"]
          .card-copy
            %h4 Venue:
            .user-activity__venue-name
              %h5= activity["venue_name"]
              %h6= activity["address_string"]

            %h4 When:
            .user-activity__date
              %h6= " #{activity["date"]} @ #{activity["time"].strip}"
            - unless "#{activity["description"]}".length == 0
              .user-activity__more-info
                %a{ id: "more-info" } More Information
                .activity__description.hidden
                  %p= activity["description"].lstrip

app/views/users/activities_update.js.erb
$('.user-activities').html('<%= j render "users/user_activities" %>')

app/views/users/dashboard.html.haml
%h2.dashboard-header #{@user.first_name}'s Activities

.sort-container
  %button.sort{:href => "#"} Name
  %button.sort{:href => "#"} Date
  %button.sort{:href => "#"} Venue


.user-activities
  = render "user_activities"